name: Periodic test pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "aeon/**"
      - ".github/workflows/**"
      - "pyproject.toml"


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
#        python-version: [ "3.9", "3.10", "3.11", "3.12" ]
        python-version: ["3.10", "3.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Use numba cache to set env variables but not restore cache
        uses: ./.github/actions/numba_cache
        with:
          cache_name: "pytest"
          runner_os: ${{ runner.os }}
          python_version: ${{ matrix.python-version }}
          restore_cache: "false"

      - uses: ./.github/actions/cpu_all_extras
        with:
          additional_extras: "dev"

      - name: Show dependencies
        run: python -m pip list

      - name: Run tests
        run: python -m pytest -n logical

      - name: Save new cache
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}/.numba_cache
          # Save cache with the current date (ENV set in numba_cache action)
          key: numba-pytest-${{ runner.os }}-${{ matrix.python-version}}-${{ env.CURRENT_DATE }}
